### ISSUE TITLE
About SoftMaskedBert

### ISSUE THREAD

**Issue by conv1d** [dutyhong/pyprojects#1]
Hi, I found an pytorch implementation of model `SoftMaskedBert` in your project.
Can you provide more files about training and data?
Thanks!

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581

**Comment by dutyhong** [comment]
you can infer to this blog https://blog.csdn.net/qq_35128926/article/details/106770581
